### ISSUE TITLE
problem in generating the .hex file

### ISSUE THREAD

**Issue by svnagendra2003** [Wiznet/Loopback_LPC11E36_LPCXpresso#3]
Hi,

We are trying to implement FTP server for our application and also purchased the W5500-EVB board just because it can handle the FTP server program. Once the testing is completed, we are planning to purchase huge number of W5500 chips.

Now we are stuck up with issues

As instructed in github as well as wiznetmuseum, i imported the project files into LPCXpresso. When trying to build, i am getting

Fatal error: “wizchip_conf.h” : No such file or directory

I tried to download the wizchip_conf.h from wiznet forum website. But, again it gives some other error.

I am stuck up and not able to compile. Please look into this matter at the earliest and provide the proper set of codes.
Also, please provide the .hex file, which I can download on to the board directly in order to test for the FTP server.

Also, i need clarifications on the following points:
1. Can i directly pass SPI data on SCK0, MISO0 and MOSI signals? Are there any modifications needed to the FTP server application code in order to pass the SPI data?

2. Can i directly pass the parallel data on pins D0, D1,..D15? are there any modifications needed to the FTP server application code in order to pass the parallel data?
please reply to email id: nagendra@ftdautomation.com

**Comment by bingdo** [comment]
Dear svnagendra2003

I guess that maybe you download project files by "Download ZIP" in a browser.
If you use "Download ZIP" in a browser, there are no source files of ioLibrary.
You must copy source files of ioLibrary to an ioLibrary directory on project.
https://github.com/Wiznet/ioLibrary_Driver

You can use SPI0. Please refer to "spiHandler.c".
D0~D15 are digital pins. You must control D0~D15 yourself to pass the parallel data.

Thanks.

**Comment by bingdo** [comment]
Refer to https://www.youtube.com/watch?v=mt815RBGdsA
Thanks.

**Comment by svnagendra2003** [comment]
Hi Bingdo,

Thanks for your email. As per your instructions, I copied the ioLibrary driver and I was able to program.

Now I am stuck up with connecting to the FTP server by using ALFTP tool.

The IP address generated after programming is : 192.168.0.91

When I enter this IP address and when I try to connect, it keeps on waiting for a long time and asks for password even though I have not entered password.

When I click OK, it tells Connection timed out error.

Please find the ppt of the screenshot attached with this email.

Please answer to this on urgent basis.

Thanks and regards,

Nagendra

**Comment by svnagendra2003** [comment]
Hi Bingdo,

Thanks for your email. As per your instructions, I copied the ioLibrary driver and I was able to program.
Now I am stuck up with connecting to the FTP server by using ALFTP tool.
The IP address generated after programming is : 192.168.0.91
When I enter this IP address and when I try to connect, it keeps on waiting for a long time and asks for password even though I have not entered password.
When I click OK, it tells Connection timed out error.

Please find the ppt of the screenshot attached with this email.

![image](https://cloud.githubusercontent.com/assets/11690789/6892378/17792c54-d6e1-11e4-9c01-20dde624bb0e.png)

Please answer to this on urgent basis.

Thanks and regards,
Nagendra

**Comment by bingdo** [comment]
Could you provide IP settings of your PC to me?
"ipconfig /all > ip.txt" in DOS window.

Thanks.

**Comment by bingdo** [comment]
Please check IP range of your PC. (FTP Client)
Is it 192.168.0.xxx?

Thanks.

**Comment by svnagendra2003** [comment]
Hi, 
My PC IP is 192.168.0.94

**Comment by svnagendra2003** [comment]
Hi,

 

Please find the ip.txt extracted from My PC attached with this email. My PC IP is 192.168.0.94.

 

 

Regards,

Nagendra

**Comment by svnagendra2003** [comment]
Hi..

Now it is working fine. I had to change my PCs IP address
Thanks for the help

**Comment by svnagendra2003** [comment]
Hi,
I was able to connect to the FTP server now. But in the server, the default directory is shown as / and a folder inside the directory by name $Recycle.bin directory. I am not able to write any new files on to the server. If i select files and if i upload the files to the server, in the Terminal i get the message as file transfer successful, but i cannot find any of the files in the / directory of the server. please let us know what is the issue and the proper solution. 
I am going to connect the SPI related signals like SCK0, MISO0 and MOSI0. I am also interested to know how will the data appear through FTP. Please reply.

**Comment by bingdo** [comment]
The last question is duplicate.
Refer to https://github.com/Wiznet/FTP_LPC11E36_LPCXpresso/issues/1

Thanks.
